# Домашне завдання №3 (2-1): Матриці та вектори (вступ до лін.алгубри)

## Ольга Шапошник

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [1]:
import numpy as np
vector = np.random.rand(10)
print(f'Vector shape: {vector.shape}')
print(f'Vector \n{vector}')

Vector shape: (10,)
Vector 
[0.20235738 0.25959405 0.21550759 0.38508955 0.4465215  0.33379137
 0.59992265 0.52668874 0.29928082 0.90422239]


In [69]:
matrix = np.array([[11, 14, 17],
                  [20 , 23, 26],
                  [29, 32, 35]])
print(f'Matrix shape: {matrix.shape}')
print(f'Matrix \n{matrix}')

Matrix shape: (3, 3)
Matrix 
[[11 14 17]
 [20 23 26]
 [29 32 35]]



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [70]:
# Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
vector = vector * 10
vector = np.round(vector, 2)
print(f'New vector *10 \n{vector}')


New vector *10 
[7.26 9.01 6.02 9.55 1.54 3.06 2.59 1.9  2.9  3.97]


In [71]:
# Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
matrix = matrix * 2
print(f'New matrix *2 \n{matrix}')

New matrix *2 
[[22 28 34]
 [40 46 52]
 [58 64 70]]


In [72]:
# Створіть новий вектор, який містить квадрат кожного `vector` без циклів.
vector_sqr = np.square(vector)
print(f'New vector with square \n{vector_sqr}')

New vector with square 
[52.7076 81.1801 36.2404 91.2025  2.3716  9.3636  6.7081  3.61    8.41
 15.7609]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [3]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [6]:
# 1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. 
# Виведіть результуючу матрицю `result_matrix` на екран.

print(f'A shape: {A.shape}')
print(f'B shape: {B.shape}')
result_matrix = np.dot(B, A)

print(f'Result matrix shape: {result_matrix.shape}')
print(f'Result matrix: \n{result_matrix}')



A shape: (3, 2)
B shape: (2, 3)
Result matrix shape: (2, 2)
Result matrix: 
[[0.7281 0.5202]
 [0.2034 0.2846]]


In [81]:
# 2. Заданий вектор `C` розмірністю 2х1. 
# Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. 
# А потім виконайте множення і виведіть результат на екран.

# Припущення:
# ми множимо матриці 2х2 на 2Х1 - отримаємо матрицю 2х1

C_new = np.dot(result_matrix, C)
print(f'C_new shape: {C_new.shape}')
print(f'C_new: \n{C_new}')


C_new shape: (2, 1)
C_new: 
[[0.5202]
 [0.2846]]


In [83]:
# 3. Задана матриця `D` розмірністю 2х2. 
# Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. 
# А потім виконайте множення і виведіть результат на екран.

# Припушення:
# ми множимо матриці 2х2 на 2Х2 - отримаємо матрицю 2х2

D_new = np.dot(result_matrix, D)
print(f'D_new shape: {D_new.shape}')
print(f'D_new: \n{D_new}')

D_new shape: (2, 2)
D_new: 
[[0.5202 0.7281]
 [0.2846 0.2034]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [86]:
# 1. Транспонуйте `result_matrix`.
transpone = result_matrix.T
print(f'Transpone shape: {transpone.shape}')
print(f'Orinal shape: {result_matrix.shape}')  

print(f'\nTranspone: \n{transpone}')
print(f'\nOrinal: \n{result_matrix}')

Transpone shape: (2, 2)
Orinal shape: (2, 2)

Transpone: 
[[0.7281 0.2034]
 [0.5202 0.2846]]

Orinal: 
[[0.7281 0.5202]
 [0.2034 0.2846]]


In [89]:
# 2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
vector_transpone = vector.T
print(f'Vector transpone shape: {vector_transpone.shape}')
print(f'Original shape: {vector.shape}')

print(f'\nVector transpone: \n{vector_transpone}')
print(f'\nOriginal: \n{vector}')


Vector transpone shape: (10,)
Original shape: (10,)

Vector transpone: 
[7.26 9.01 6.02 9.55 1.54 3.06 2.59 1.9  2.9  3.97]

Original: 
[7.26 9.01 6.02 9.55 1.54 3.06 2.59 1.9  2.9  3.97]


**Висновок**: При транспонуванні вектора ніяких змін не відбувається. Його розмір залишається таким самими (10,)


In [91]:
# 3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. 
# Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.

column_vector = np.expand_dims(vector, axis=1)
print(f'Column vector shape: {column_vector.shape}')
print(f'Original shape: {vector.shape}')    

print(f'\nColumn vector: \n{column_vector}')
print(f'\nOriginal: \n{vector}')

Column vector shape: (10, 1)
Original shape: (10,)

Column vector: 
[[7.26]
 [9.01]
 [6.02]
 [9.55]
 [1.54]
 [3.06]
 [2.59]
 [1.9 ]
 [2.9 ]
 [3.97]]

Original: 
[7.26 9.01 6.02 9.55 1.54 3.06 2.59 1.9  2.9  3.97]


**Висновок**. 
Використання numpy.expand_dims з аргументом axis=1 призводить до зміни/додавання додаткової розмірності до вектора. МИ перетворили вектор на матрицю з одним стовпцем (10,1)



In [92]:
# 4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.
column_vector_transpone = column_vector.T
print(f'Column vector transpone shape {column_vector_transpone.shape}')

print(f'\nColumn vector transpone: \n{column_vector_transpone}')

Column vector transpone shape (1, 10)

Column vector transpone: 
[[7.26 9.01 6.02 9.55 1.54 3.06 2.59 1.9  2.9  3.97]]


**Висновок** Транспонування Column vector змінює рядки та стовпці місцями. Транспонування змінило Column vector з одного вертикального стовпця на горизонтальний рядок

РОзмірність:
- стало (1, 10)
- було (10, 1)
