#  Matrices and Vectors (Introduction to Linear Algebra)

### Task 1: Creating Matrices and Vectors
1. Create a `numpy` vector `vector` of dimension 10 with random real values ​​in the range from 0 to 1. You can use two alternative options:
  1. Generate random numbers with the [`random.uniform`](https://docs.python.org/3/library/random.html) module.
  2. Creating a vector using the `numpy` method [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Create a `matrix` of type `numpy.array` of dimension 3x3 with the following values

$$
matrix = \begin{bmatrix}
11 & 14 & 17 \\
20 & 23 & 26 \\
29 & 32 & 35
\end{bmatrix}
$$

by any method known to you.

Print the vector and matrix, as well as their dimensions, on the screen.

In [1]:
import numpy as np
vector = np.random.rand(10)
print(f'Vector shape: {vector.shape}')
print(f'Vector \n{vector}')

Vector shape: (10,)
Vector 
[0.20235738 0.25959405 0.21550759 0.38508955 0.4465215  0.33379137
 0.59992265 0.52668874 0.29928082 0.90422239]


In [69]:
matrix = np.array([[11, 14, 17],
                  [20 , 23, 26],
                  [29, 32, 35]])
print(f'Matrix shape: {matrix.shape}')
print(f'Matrix \n{matrix}')

Matrix shape: (3, 3)
Matrix 
[[11 14 17]
 [20 23 26]
 [29 32 35]]


### Task 2: Operations on vectors and matrices
Perform each of the following operations on the specified objects and display the result:
1. Add 10 to each value of the vector `vector` and round each value to 2 decimal places without using loops.
2. Multiply each element of the matrix from the first task by 2 without using loops.
3. Create a new vector that contains the square of each `vector` without using loops.

In [ ]:
# Add 10 to each value of the vector `vector` and round each value to 2 decimal places without using loops.
vector = vector * 10
vector = np.round(vector, 2)
print(f'New vector *10 \n{vector}')


New vector *10 
[7.26 9.01 6.02 9.55 1.54 3.06 2.59 1.9  2.9  3.97]


In [ ]:
# Multiply each element of the matrix from the first problem by 2 without using loops.
matrix = matrix * 2
print(f'New matrix *2 \n{matrix}')

New matrix *2 
[[22 28 34]
 [40 46 52]
 [58 64 70]]


In [ ]:
# Create a new vector that contains the square of each `vector` without cycles.
vector_sqr = np.square(vector)
print(f'New vector with square \n{vector_sqr}')

New vector with square 
[52.7076 81.1801 36.2404 91.2025  2.3716  9.3636  6.7081  3.61    8.41
 15.7609]


### Task 3: Matrix Multiplication
1. Given two matrices `A` and `B` with dimensions 3x2 and 2x3. Multiply them to get a 2x2 matrix. Display the resulting matrix `result_matrix` on the screen.

2. Given a vector `C` with dimension 2x1. First think about what dimension you will get when you multiply `result_matrix` by the vector `C` and what the result will be. And then perform the multiplication and display the result on the screen.

3. Given a matrix `D` with dimension 2x2. First think about what dimension you will get when you multiply `result_matrix` by the matrix `D` and what the result will be. And then perform the multiplication and display the result on the screen.

In [3]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [ ]:
# 1. Given two matrices `A` and `B` of dimensions 3x2 and 2x3. Multiply them to get a 2x2 matrix.
# Print the resulting matrix `result_matrix` to the screen.

print(f'A shape: {A.shape}')
print(f'B shape: {B.shape}')
result_matrix = np.dot(B, A)

print(f'Result matrix shape: {result_matrix.shape}')
print(f'Result matrix: \n{result_matrix}')



A shape: (3, 2)
B shape: (2, 3)
Result matrix shape: (2, 2)
Result matrix: 
[[0.7281 0.5202]
 [0.2034 0.2846]]


In [ ]:
# 2. Given a vector `C` of dimension 2x1.
# First think about what dimension you will get when you multiply `result_matrix` by the vector `C` and what the result will be.
# And then perform the multiplication and display the result on the screen.

# Assumptions:
# we multiply 2x2 matrices by 2X1 - we will get a 2x1 matrix

C_new = np.dot(result_matrix, C)
print(f'C_new shape: {C_new.shape}')
print(f'C_new: \n{C_new}')


C_new shape: (2, 1)
C_new: 
[[0.5202]
 [0.2846]]


In [ ]:
# 3. Given a matrix `D` of dimension 2x2.
# First think about what dimension you will get when you multiply `result_matrix` by matrix `D` and what the result will be.
# And then perform the multiplication and display the result on the screen.

# Assumptions:
# we multiply matrices 2x2 by 2X2 - we will get a matrix 2x2

D_new = np.dot(result_matrix, D)
print(f'D_new shape: {D_new.shape}')
print(f'D_new: \n{D_new}')

D_new shape: (2, 2)
D_new: 
[[0.5202 0.7281]
 [0.2846 0.2034]]


### Task 4: Transpose matrices
1. Transpose `result_matrix`.
2. Transpose the vector `vector` and print the shape of the new structure. Do you see the change?
3. Use the `numpy.expand_dims` operation on the vector `vector` with the argument axis=1. Write the result to the variable `column_vector` and print it. Compare it with `vector`.
4. Transpose the `column_vector` and print the result along with the dimensions of the resulting structure.



In [ ]:
# 1. Transpose `result_matrix`.
transpone = result_matrix.T
print(f'Transpone shape: {transpone.shape}')
print(f'Orinal shape: {result_matrix.shape}')  

print(f'\nTranspone: \n{transpone}')
print(f'\nOrinal: \n{result_matrix}')

Transpone shape: (2, 2)
Orinal shape: (2, 2)

Transpone: 
[[0.7281 0.2034]
 [0.5202 0.2846]]

Orinal: 
[[0.7281 0.5202]
 [0.2034 0.2846]]


In [ ]:
# 2. Take the transpose of the vector `vector` and output the shape for the new structure. Do you see the change?
vector_transpone = vector.T
print(f'Vector transpone shape: {vector_transpone.shape}')
print(f'Original shape: {vector.shape}')

print(f'\nVector transpone: \n{vector_transpone}')
print(f'\nOriginal: \n{vector}')


Vector transpone shape: (10,)
Original shape: (10,)

Vector transpone: 
[7.26 9.01 6.02 9.55 1.54 3.06 2.59 1.9  2.9  3.97]

Original: 
[7.26 9.01 6.02 9.55 1.54 3.06 2.59 1.9  2.9  3.97]


In [ ]:
# 3. Use the `numpy.expand_dims` operation on the `vector` vector with the argument axis=1.
# Write the result to the `column_vector` variable and print it. Compare it with `vector`.

column_vector = np.expand_dims(vector, axis=1)
print(f'Column vector shape: {column_vector.shape}')
print(f'Original shape: {vector.shape}')    

print(f'\nColumn vector: \n{column_vector}')
print(f'\nOriginal: \n{vector}')

Column vector shape: (10, 1)
Original shape: (10,)

Column vector: 
[[7.26]
 [9.01]
 [6.02]
 [9.55]
 [1.54]
 [3.06]
 [2.59]
 [1.9 ]
 [2.9 ]
 [3.97]]

Original: 
[7.26 9.01 6.02 9.55 1.54 3.06 2.59 1.9  2.9  3.97]


**Conclusion**.
Using numpy.expand_dims with axis=1 changes/adds an extra dimension to the vector. WE have converted the vector to a matrix with one column (10,1)



In [ ]:
# 4. Transpose `column_vector`, output the result to the screen along with the dimensions of the resulting structure.
column_vector_transpone = column_vector.T
print(f'Column vector transpone shape {column_vector_transpone.shape}')

print(f'\nColumn vector transpone: \n{column_vector_transpone}')

Column vector transpone shape (1, 10)

Column vector transpone: 
[[7.26 9.01 6.02 9.55 1.54 3.06 2.59 1.9  2.9  3.97]]


**Conclusion** Transposing a Column vector swaps rows and columns. Transposing changed the Column vector from one vertical column to a horizontal row

Dimension:
- became (1, 10)
- was (10, 1)
